#!/bin/bash
#
#  bwrgod The bwrgo Core server.
#
#
# chkconfig: 345 80 20
# description: bwrgod
# processname: bwrgod
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/bwrgod, see below
if [ -f /etc/sysconfig/bwrgod ]; then
        . /etc/sysconfig/bwrgod
fi

RETVAL=0

prog=bwrgod
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/bwrgod
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/bwrgod}

# bwrgod defaults to /usr/bin/bwrgod, override with BITCOIND_BIN
bwrgod=${BITCOIND_BIN-/usr/bin/bwrgod}

# bwrgod opts default to -disablewallet, override with BITCOIND_OPTS
bwrgod_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $bwrgod $bwrgod_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
